package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/stasundr/gqlgen-pg-todo-example/graph/model"
)

// TodoCreate is the resolver for the todoCreate field.
func (r *mutationResolver) TodoCreate(ctx context.Context, todo model.TodoInput) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoCreate - todoCreate"))
}

// TodoComplete is the resolver for the todoComplete field.
func (r *mutationResolver) TodoComplete(ctx context.Context, id int, updatedBy int) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoComplete - todoComplete"))
}

// TodoDelete is the resolver for the todoDelete field.
func (r *mutationResolver) TodoDelete(ctx context.Context, id int, updatedBy int) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: TodoDelete - todoDelete"))
}

// UserCreate is the resolver for the userCreate field.
func (r *mutationResolver) UserCreate(ctx context.Context, user model.UserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserCreate - userCreate"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
